export const ADD_APPOINTMENT = 'ADD_APPOINTMENT'
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT'
export const EDIT_APPOINTMENT = 'EDIT_APPOINTMENT'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'

export const FETCH_APPOINTMENTS_REQUEST	= '@app/FETCH_APPOINTMENTS_REQUEST'  
export const FETCH_APPOINTMENTS_SUCCESS	= '@app/FETCH_APPOINTMENTS_SUCCESS'
export const FETCH_APPOINTMENTS_FAILURE	= '@app/FETCH_APPOINTMENTS_FAILURE'

export const ADD_APPOINTMENT_REQUEST	= '@app/ADD_APPOINTMENT_REQUEST'  
export const ADD_APPOINTMENT_SUCCESS	= '@app/ADD_APPOINTMENT_SUCCESS'
export const ADD_APPOINTMENT_FAILURE	= '@app/ADD_APPOINTMENT_FAILURE'

export const DELETE_APPOINTMENT_REQUEST	= '@app/DELETE_APPOINTMENT_REQUEST'  
export const DELETE_APPOINTMENT_SUCCESS	= '@app/DELETE_APPOINTMENT_SUCCESS'
export const DELETE_APPOINTMENT_FAILURE	= '@app/DELETE_APPOINTMENT_FAILURE'

export const EDIT_APPOINTMENT_REQUEST	= '@app/EDIT_APPOINTMENT_REQUEST'  
export const EDIT_APPOINTMENT_SUCCESS	= '@app/EDIT_APPOINTMENT_SUCCESS'
export const EDIT_APPOINTMENT_FAILURE	= '@app/EDIT_APPOINTMENT_FAILURE'
